### ISSUE TITLE
Job does not finish, but keeps printing memory values. I stopped it.

### ISSUE THREAD

**Issue by MizioAnd** [MizioAnd/pythonWrapper#8]
Memory: 3.97674942017
Memory: 3.97674942017
Memory: 3.97674942017
Memory: 3.97674942017
Memory: 3.97674942017
Memory: 3.97674942017
Memory: 3.97674942017
Memory: 3.97674942017
Memory: 3.97674942017
Traceback (most recent call last):
  File "/Users/mizio/Documents/MizioSpatafora/PycharmProjects/pythonWrapper/runner/client/client.py", line 128, in <module>
    c.execute()
  File "/Users/mizio/Documents/MizioSpatafora/PycharmProjects/pythonWrapper/runner/client/client.py", line 113, in execute
    raise ValueError("Run failed")
ValueError: Run failed

**Comment by MizioAnd** [comment]
Should have returned,

Starting parallel pool (parpool) using the 'local' profile ... connected to 5 workers.
Parallel pool using the 'local' profile is shutting down.
Attempted to access A(60,1); index out of bounds because size(A)=[10,1].

Error in @(A)A(yCoord_plot,1)


Error in LinTimelyOscSolCurrent (line 2042)
            currentPlotChem_sliced = 1/(2i*sqrt(2))*(cellfun(subindex_cellfun, matrixToPlotXY_valuesOfCurrent_paramag_xdir));
 
>>

**Comment by sposs** [comment]
If I work on this today, do you have time to try it out?

**Comment by MizioAnd** [comment]
Yes, there is time for tests.

**Comment by sposs** [comment]
Ok, what is the command to send to exit matlab? Is 'exit' enough?

**Comment by sposs** [comment]
And what is the command to save the environment?

**Comment by MizioAnd** [comment]
OK, the server has over night changed the name on open ports. 

(matlabEnv)mizio@Mac-Pro-de-Cristiano:~$  telnet th1.mpq.univ-paris-diderot.fr 47801
Trying 81.194.18.242...
telnet: connect to address 81.194.18.242: Connection refused
telnet: Unable to connect to remote host


I will run:
python setup.py install
To see what happens.

**Comment by MizioAnd** [comment]
1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1

Command "/Users/mizio/.virtualenvs/matlabEnv/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/_n/8_b4zpn5173258s61pnx0b1w0000gp/T/pip-build-GXKuGG/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/_n/8_b4zpn5173258s61pnx0b1w0000gp/T/pip-v6THn7-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/mizio/.virtualenvs/matlabEnv/bin/../include/site/python2.7/psutil" failed with error code 1 in /private/var/folders/_n/8_b4zpn5173258s61pnx0b1w0000gp/T/pip-build-GXKuGG/psutil

**Comment by sposs** [comment]
My bad... Will fix.

2015-04-13 15:43 GMT+02:00 MizioAnd <notifications@github.com>:

**Comment by sposs** [comment]
Actually, the python setup.py install should be ran only on th1, not on your machine. psutil does not install properly on osx.

**Comment by MizioAnd** [comment]
Ok, do I need to run it in a virtual env on th1?

without it results in:

running install_lib
    copying build/lib.linux-x86_64-2.7/_psutil_posix.so -> /usr/local/lib/python2.7/dist-packages
    error: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/_psutil_posix.so'

Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-WMhlYm/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-WBtWQa-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-WMhlYm/psutil
error: ['/usr/bin/python', u'-m', u'pip.__init__', u'install', u'pbr', u'psutil', u'jsonrpclib', u'pyzmq'] returned 1

**Comment by sposs** [comment]
Yes, you need to log on th1, then
- source virtualenvwrapper.sh
- workon matlabEnv 
- cd pythonWrapper 
- git pull
- python setup.py install

**Comment by sposs** [comment]
Don't forget to merge the pull request before git pull on th1!

**Comment by MizioAnd** [comment]
Thanks, my server_runner works fine without the pull request.

I will now do the same again to test the pull request.

**Comment by MizioAnd** [comment]
-- Ok, what is the command to send to exit matlab? Is 'exit' enough?

exit

-- And what is the command to save the environment?

save(['environmentName', '.mat']);

one may want to change the format. So lets go with.

save(['environmentName]);

**Comment by sposs** [comment]
Ok, I'll ad the exit and the environmentName as option to be specified by the user (in the client)

**Comment by MizioAnd** [comment]
the job was not able to run.

/Users/mizio/.virtualenvs/matlabEnv/bin/python /Users/mizio/Documents/MizioSpatafora/PycharmProjects/pythonWrapper/runner/client/client.py
Connecting to http://th1.mpq.univ-paris-diderot.fr:47801
At revision 235.
Traceback (most recent call last):
  File "/Users/mizio/Documents/MizioSpatafora/PycharmProjects/pythonWrapper/runner/client/client.py", line 128, in <module>
    c.execute()
  File "/Users/mizio/Documents/MizioSpatafora/PycharmProjects/pythonWrapper/runner/client/client.py", line 102, in execute
    res = self._server.execute(self._pdict, cleanup)
  File "/Users/mizio/.virtualenvs/matlabEnv/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 274, in __call__
    return self.__send(self.__name, args)
  File "/Users/mizio/.virtualenvs/matlabEnv/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 225, in _request
    check_for_errors(response)
  File "/Users/mizio/.virtualenvs/matlabEnv/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 529, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error:   File "/home/andersen/.virtualenvs/matlabEnv/local/lib/python2.7/site-packages/runner/server/main.py", line 109, in execute | OSError: [Errno 2] No such file or directory: \'/home/andersen/current/current/\'')

Process finished with exit code 1

**Comment by sposs** [comment]
Because after you updated, you need to run the server from your home directory on that host, i.e. /home/andersen

The last option in the command line is the repo-path, it must be /home/andersen/current

**Comment by MizioAnd** [comment]
It was done like that. And it gives the same error message

Traceback (most recent call last):
  File "/Users/mizio/Documents/MizioSpatafora/PycharmProjects/pythonWrapper/runner/client/client.py", line 128, in <module>
    c.execute()
  File "/Users/mizio/Documents/MizioSpatafora/PycharmProjects/pythonWrapper/runner/client/client.py", line 102, in execute
    res = self._server.execute(self._pdict, cleanup)
  File "/Users/mizio/.virtualenvs/matlabEnv/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 274, in __call__
    return self.__send(self.__name, args)
  File "/Users/mizio/.virtualenvs/matlabEnv/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 225, in _request
    check_for_errors(response)
  File "/Users/mizio/.virtualenvs/matlabEnv/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 529, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error:   File "/home/andersen/.virtualenvs/matlabEnv/local/lib/python2.7/site-packages/runner/server/main.py", line 109, in execute | OSError: [Errno 2] No such file or directory: \'/home/andersen/current/current/\'')

Process finished with exit code 1

**Comment by sposs** [comment]
Can you send me the exact command line you passed?

**Comment by MizioAnd** [comment]
(matlabEnv)andersen@th1:~$ cd pythonWrapper/
(matlabEnv)andersen@th1:~/pythonWrapper$ git pull
Already up-to-date.
(matlabEnv)andersen@th1:~/pythonWrapper$ cd ..
(matlabEnv)andersen@th1:~$ cd current/
(matlabEnv)andersen@th1:~/current$ cd ..
(matlabEnv)andersen@th1:~$ cd pythonWrapper/
(matlabEnv)andersen@th1:~/pythonWrapper$ python setup.py install
(matlabEnv)andersen@th1:~/pythonWrapper$ cd ..
(matlabEnv)andersen@th1:~$ cd current/
(matlabEnv)andersen@th1:~/current$ server_runner -p 47801  --host th1.mpq.univ-paris-diderot.fr --repo-path `pwd`/current/

**Comment by MizioAnd** [comment]
dont mind the intermediate jump to current before python setup.py was typed.

**Comment by sposs** [comment]
then the last line is NOT what I said. You need to be running from /home/andersen, or the --repo-path should be --repo-path .

**Comment by sposs** [comment]
"--repo-path .", the "." being the local directory

**Comment by MizioAnd** [comment]
True. The memory print out worked, but then,


Memory: 2.9397315979
Memory: 2.9397315979
Traceback (most recent call last):
  File "/Users/mizio/Documents/MizioSpatafora/PycharmProjects/pythonWrapper/runner/client/client.py", line 128, in <module>
    c.execute()
  File "/Users/mizio/Documents/MizioSpatafora/PycharmProjects/pythonWrapper/runner/client/client.py", line 102, in execute
    res = self._server.execute(self._pdict, cleanup)
  File "/Users/mizio/.virtualenvs/matlabEnv/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 274, in __call__
    return self.__send(self.__name, args)
  File "/Users/mizio/.virtualenvs/matlabEnv/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 225, in _request
    check_for_errors(response)
  File "/Users/mizio/.virtualenvs/matlabEnv/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 529, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error: delaybeforesend: 0.05 | delayafterterminate: 0.1')

**Comment by sposs** [comment]
Sorry for the delay! This problems comes from the fact that the command did not behave the way I thought it would. Will propose a fix.

**Comment by sposs** [comment]
I suspect the program fails after roughly 30 seconds of running...

**Comment by sposs** [comment]
I'll need to know some 'expected' and 'reasonable' value for the duration of a run. Indeed, the tool I use to run the program requires that there is a timeout set after which the job is killed. This is what you observed. The default is 30 seconds.

**Comment by sposs** [comment]
Fixed by #10 in principle

**Comment by MizioAnd** [comment]
Yes, program failed after 30 sec. And it then went on setting over processes for like 1-2 min. after the "Process finished with exit code 1" comment in pycharm.

I will now merge your pull request. And I will test it.

**Comment by MizioAnd** [comment]
It works. Have a nice weekend.

Print from job:

Memory: 0.0118713378906
date 			 message 		 cpu 	 outputdir 	 time 	 peak_mem 	 avg_mem
2015-04-17 16:44:36.568874	Test of pythonwrapper on th1 of conductivity in x-dir, matchingPlot params	 0-5	 testSpaces/testSpace20150412/YdirConductivity/testDiamag/matchingPlot/smallSys	 0:01:56.400819	 3.92074966431	 3.52728369477
set affinity to CPUs 0-5
[?1h=
                            < M A T L A B (R) >
                  Copyright 1984-2014 The MathWorks, Inc.
                    R2014a (8.3.0.532) 64-bit (glnxa64)
                             February 11, 2014

 
To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.
 
[?1h=[?1h=
pc = 

 Local Cluster

    Properties: 

                          Profile: local
                         Modified: true
                             Host: th1
                       NumWorkers: 6

               JobStorageLocation: /tmp/matlab_andersen_2015-04-17_18-42-36/
 RequiresMathWorksHostedLicensing: false

    Associated Jobs: 

                   Number Pending: 0
                    Number Queued: 0
                   Number Running: 0
                  Number Finished: 0

Starting parallel pool (parpool) using the 'local' profile ... connected to 6 workers.
Parallel pool using the 'local' profile is shutting down.
[?1h=[?1h=
pc = 

 Local Cluster

    Properties: 

                          Profile: local
                         Modified: true
                             Host: th1
                       NumWorkers: 6

               JobStorageLocation: /tmp/matlab_andersen_2015-04-17_18-43-52/
 RequiresMathWorksHostedLicensing: false

    Associated Jobs: 

                   Number Pending: 0
                    Number Queued: 0
                   Number Running: 0
                  Number Finished: 0

Starting parallel pool (parpool) using the 'local' profile ... connected to 6 workers.
Parallel pool using the 'local' profile is shutting down.
[?1h=Elapsed time is 107.201750 seconds.
[?1l>

Process finished with exit code 0
